#!/bin/sh

main() {
    determine_migration_file_name $1
    copy_migration_file
    show_migration_file_name
}

determine_migration_file_name() {
    MIGRATION_FILE_NAME=$(date +'%Y%m%d%H%M')_${1}.sql
}

copy_migration_file() {
    cp db/migration-scaffold.sql db/migrations/${MIGRATION_FILE_NAME}
}

show_migration_file_name() {
    printf "db/migrations/%s\n" "$MIGRATION_FILE_NAME"
}

main "$@"
