global.$ = global.jQuery = require 'jquery'
global.angular = require 'angular'
require 'messageformat'
global.moment = require 'moment'
require 'later'

require 'angular-animate'
require 'angular-messages'
require 'angular-resource'
require '../bower_components/angular-flash/dist/angular-flash'
require '../bower_components/angular-moment/angular-moment'
require '../bower_components/ng-focus-if/focusIf'
require '../bower_components/angular-ga/ga'
require '../bower_components/ngprogress-lite/ngprogress-lite'
require '../bower_components/angular-translate/angular-translate'
require '../bower_components/angular-translate-interpolation-messageformat/angular-translate-interpolation-messageformat'
require '../bower_components/ng-toggle/toggles'
require '../bower_components/angular-gravatar/build/angular-gravatar'
require '../bower_components/angular-ui-router/release/angular-ui-router'
require '../bower_components/angular-ui-router/release/stateEvents'
require './scripts/vendor/ui-router-history'
require '../bower_components/angular-inflector/dist/angular-inflector'
require '../bower_components/angular-flash/dist/angular-flash'
require '../bower_components/braintree-web/dist/braintree'
