#!/bin/sh -eu

ENVS="production"

# if [ -n "$(git diff --shortstat 2>/dev/null | tail -n1)" ]; then
#   printf "\n\n\nRefusing to dist on a dirty working tree\n" >&2
#   exit 1
# fi

obj_name() {
  # printf "s3://harrow-frontend/%s-%s/dist.tar.gz" "$(git rev-parse --short HEAD)" "$1"
  printf "frontend/%s-%s/dist.tar.gz" "$(git rev-parse --short HEAD)" "$1"
}

for e in $ENVS; do
  HARROW_ENV=$e npm run build
  (
    tmp=$(mktemp /tmp/fe-dist.XXXXXXXXXX)
    cd dist
    tar -czf $tmp .
    AWS_PROFILE=harrow-build-deploy aws s3api put-object --bucket harrow-builds --key "$(obj_name "$e")" --body $tmp
    unlink $tmp
  )
done

ref="refs/releases/$(date -u +%Y-%m-%dT%H_%M_%S+00_00)"
git update-ref "${ref}" HEAD
git push origin "${ref}":"${ref}"
