production:
	ANSIBLE_CONFIG=./ansible.cfg ansible-playbook --inventory=./inventories/production provision.yml

# development:
# 	ANSIBLE_CONFIG=./ansible.cfg vagrant up dev --provision
#
# appliance:
# 	ANSIBLE_CONFIG=./ansible.cfg vagrant up appliance --provision

.PHONY: production
# .PHONY: production development enterprise
