---

- apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - libpq-dev
    - "postgresql={{harrow.postgresql.version}}*"
    - python-psycopg2

- name: stop postgresql before lobotomising it
  systemd:
    name: postgresql
    state: stopped

- name: "/var/lib/harrow/postgresql/{{harrow.postgresql.version}}/main"
  file:
    state: directory
    path: "/var/lib/harrow/postgresql/{{harrow.postgresql.version}}/main"
    owner: postgres
    group: postgres

- name: set postgresql data_directory
  lineinfile:
   dest: "/etc/postgresql/{{harrow.postgresql.version}}/main/postgresql.conf"
   regexp: '^data_directory ='
   line: "data_directory = '/var/lib/harrow/postgresql/{{harrow.postgresql.version}}/main'"
  become: true

- name: 'fix postgresql permissions'
  file:
    path: /var/lib/harrow/postgresql/
    owner: postgres
    group: postgres
    mode: 0700
    recurse: true
  become: true

# - name: 'check for postgresql dir files (must init?)'
#   find:
#     paths: /var/lib/harrow/postgresql
#     file_type: file
#     patterns: "*"
#   register: postgresql_dir_files

- name: initiate database
  command: "/usr/lib/postgresql/{{harrow.postgresql.version}}/bin/initdb -D /var/lib/harrow/postgresql/{{harrow.postgresql.version}}/main"
  become: true
  become_user: postgres
  ignore_errors: true

- replace:
    dest: "{{ item }}"
    regexp: 'local.*all.*all.*peer'
    replace: "local   all             all                                     password"
  with_items:
    - "/etc/postgresql/{{harrow.postgresql.version}}/main/pg_hba.conf"
    - "/var/lib/harrow/postgresql/{{harrow.postgresql.version}}/main/pg_hba.conf"
  become: true

- lineinfile:
    dest: "{{ item }}"
    regexp: 'local.*all.*all.*password'
    line: "local   all             all                                     trust"
  with_items:
    - "/etc/postgresql/{{harrow.postgresql.version}}/main/pg_hba.conf"
    - "/var/lib/harrow/postgresql/{{harrow.postgresql.version}}/main/pg_hba.conf"
  become: true

- name: start post-lobotomy postgresql
  systemd:
    name: postgresql
    state: restarted

- postgresql_db:
    name: "{{ db.name }}"
    encoding: "UTF-8"
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: "template0"
    owner: 'postgres'
  with_items: "{{ harrow.postgresql.databases }}"
  loop_control:
    loop_var: db
  become: true
  become_user: postgres

- name: "create postgresql user {{ db.username }}"
  postgresql_user:
    db: "{{ db.name }}"
    name: "{{ db.username }}"
    password: "{{ db.password }}"
  with_items: "{{ harrow.postgresql.databases }}"
  loop_control:
    loop_var: db
  become: true
  become_user: postgres

- copy:
    dest: "/etc/tmpfiles.d/postgresql-{{harrow.postgresql.version}}.conf"
    content: "D /var/run/postgresql 0775 - postgres -"
  notify: restart postgresql

- include: pgbouncer.yml
- include: postgresql_extensions.yml
- include: firewall.yml
